<?php

namespace AppBundle\Repository;

/**
 * NovaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NovaRepository extends \Doctrine\ORM\EntityRepository
{
}
