<?php

namespace UsuarioBundle\Repository;

/**
 * PadraoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItensPedidoRepository extends \Doctrine\ORM\EntityRepository
{

    public function buscarItensPedidoPedido($pedido)
    {

        return $this->getEntityManager()
            ->createQuery(
                "SELECT p FROM UsuarioBundle:ItensPedido p WHERE p.pedidopedido = :pedido"
            )->setParameter('pedido',$pedido)
            ->getResult();
    }
}
