<?php

namespace UsuarioBundle\Repository;

/**
 * PadraoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoginRepository extends \Doctrine\ORM\EntityRepository
{
    public function buscarUltimoLogin()
    {

        return $this->getEntityManager()
            ->createQuery(
                "SELECT l FROM UsuarioBundle:Login l WHERE l.id = (select MAX(li.id) from UsuarioBundle:Login li)"
            )
            ->getResult();
    }



}
