<?php

namespace UsuarioBundle\Repository;

/**
 * PadraoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoginRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBuscarUltimoLogin()
    {

        return $this->getEntityManager()
            ->createQuery(
                "SELECT l FROM UsuarioBundle:Login l WHERE l.id = (select MAX(li.id) from UsuarioBundle:Login li)"
            )
            ->getSingleResult();
    }

    public function buscaLogin($login,$senha)
    {
        $existe=$this->getEntityManager()
            ->createQuery(
                "SELECT l FROM UsuarioBundle:Login l where l.login = :login and l.senha = :senha"
            )->setParameter('login',$login)
            ->setParameter('senha',$senha)
            ->getResult();

        return $existe;
    }



}
