<?php

namespace UsuarioBundle\Repository;

/**
 * PadraoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidoRepository extends \Doctrine\ORM\EntityRepository
{
    public function BuscarUltimoPagamentoUsuario($usuario)
    {

        return $this->getEntityManager()
            ->createQuery(
                "SELECT p FROM UsuarioBundle:Pedido p WHERE p.idpedido = (select MAX(pa.idpedido) from UsuarioBundle:Pedido pa) and p.idusuario = :usuario"
            )->setParameter('usuario',$usuario)
            ->getSingleResult();
    }

    public function buscaPedidoValido($usuario)
    {

        return $this->getEntityManager()
            ->createQuery(
                "SELECT p FROM UsuarioBundle:Pedido p WHERE p.idusuario = :usuario and p.status <> 'fase1'"
            )->setParameter('usuario',$usuario)
            ->getResult();
    }
}
