<?php

namespace UsuarioBundle\Repository;

/**
 * PadraoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends \Doctrine\ORM\EntityRepository
{
    public function buscaUsuario($login)
    {

        return $this->getEntityManager()
            ->createQuery(
                "SELECT u FROM UsuarioBundle:Usuario u where u.idlogin =".$login
            )
            ->getSingleResult();
    }
}
